[package]
name = "kreta-combine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
kreta-rs.workspace = true
tokio ={ workspace = true, features = ["macros"] }
